// NOTE: All robots, makers, model names and specs below are FICTIONAL PLACEHOLDERS.
// No real manufacturer (EngineAI, Booster Robotics, LimX Dynamics, PNDbotics, Fourier,
// or any other real company) has agreed to be represented by this business yet.
// These entries stand in for the real lineup and will be replaced once real
// manufacturer partnerships are signed. Do not reintroduce real brand/model names
// or real product photography here until that happens.
export const ROBOTS = [
  {
    slug: "ironvale-c1",
    name: "Ironvale C1",
    maker: "Ironvale Robotics",
    kicker: "Ironvale Robotics — compact humanoid",
    cls: "Compact humanoid · 22 DOF",
    chips: ["Education", "Competition"],
    badges: ["CE docs verified", "Multi-unit pricing"],
    proof: "Designed for competitions and classroom fleets",
    rating: null,
    reviewCount: null,
    image: null,
    gallery: [],
    price: "from $5,000",
    priceNum: "5000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "The lowest-cost humanoid in the lineup we plan to represent — and the easiest first “yes” for a department budget. Force-controlled joints, a full sensor suite, and the same developer DNA as Ironvale's flagship D1, in a compact ~20 kg frame a classroom can handle safely.",
    useCases: [
      ["Education", "Teaching platforms for robotics, control and AI courses — priced so a program can buy several."],
      ["Competition", "Built with robotics competitions and university coursework squarely in mind."],
      ["Entry research", "HRI and locomotion work before committing to a full-size platform."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Multi-unit education pricing available on request",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Class", "Compact humanoid, ~20 kg"],
      ["Degrees of freedom", "22, force-controlled joints"],
      ["Motion", "Human-like walking and gestures"],
      ["Perception", "3D depth camera, 9-axis IMU, microphone array, touch sensors"],
      ["Intended use", "Education, research, competition"],
      ["Indicative price", "from $5,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 118, torso: [124, 150, 52, 64], dim: "compact class", dimTop: 96 },
    faq: [
      ["Is $5,000 really the price of a humanoid robot?", "As the indicative ex-works base for the C1, yes — it's the entry point of the current Chinese humanoid wave. Landed cost in the EU adds freight, duty and VAT; your quote itemizes the real delivered number for your country."],
      ["Can a school or university buy several for a course?", "That's the C1's natural habitat. Tell us the quantity on the quote form — multi-unit education pricing is one of the first things we negotiate with the factory."],
      ["C1 or M2 for a first robot?", "C1 if budget rules or you're equipping a class. M2 if you want a bigger frame and more onboard compute for research-grade AI workloads. Both are safe first orders."],
      ["How long does delivery to Europe take?", "It depends on factory stock and freight mode — air versus sea is the big fork. Your quote states the current lead time before you commit."],
    ],
    meta: {
      title: "Ironvale C1 — Price & Specs | Humanoid Robot for Education | Humanoid Hub",
      description: "Ironvale C1 compact humanoid: from $5,000, 22 DOF, depth camera, built for education and competitions. Buy the C1 in Europe or the Middle East — quote in one business day.",
      ldDescription: "Compact humanoid robot for education, research and competition. 22 degrees of freedom, force-controlled joints, 3D depth camera.",
    },
  },
  {
    slug: "halcyon-m2",
    name: "Halcyon M2",
    maker: "Halcyon Robotics",
    kicker: "Halcyon Robotics — mid-size humanoid",
    cls: "Mid-size humanoid · 24 DOF",
    chips: ["Research", "Content", "Education"],
    badges: ["CE docs verified", "Hub first pick"],
    proof: "Built for agile, expressive movement",
    rating: null,
    reviewCount: null,
    image: null,
    gallery: [],
    price: "from $12,000",
    priceNum: "12000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "The robot positioned to make humanoids affordable. 1.38 m, 24 degrees of freedom, a 320° rotating waist, and enough onboard compute to run real AI workloads — at a price a single research grant covers. The M2 is the platform we plan to recommend first to most labs and education programs in EMEA.",
    useCases: [
      ["Research labs", "Locomotion, HRI and embodied-AI work on a budget that leaves room for a second unit."],
      ["Education", "Engineering and robotics programs that need hardware students can actually touch."],
      ["Content & events", "The M2's dynamic movement is built to draw crowds at expos and on camera."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "EU deliveries: CE documentation verified first",
      "University procurement paperwork supported",
    ],
    specs: [
      ["Height", "1.38 m"],
      ["Weight", "40 kg"],
      ["Degrees of freedom", "24 total, incl. 320° waist rotation"],
      ["Compute", "Dual-processor: Intel N97 + NVIDIA Jetson Orin"],
      ["Mobility", "Dynamic walking and high-agility maneuvers"],
      ["Intended use", "Commercial, research and educational deployment"],
      ["Indicative price", "from $12,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 60, torso: [122, 92, 56, 86], dim: "1.38 m", dimTop: 38 },
    faq: [
      ["How do I buy the Halcyon M2 in Europe?", "Request a quote through us. We confirm current configuration and lead time with the manufacturer, verify the CE documentation needed for your EU destination, and return a formal quote — typically within one business day."],
      ["What does the M2 really cost delivered?", "The $12,000 figure is the manufacturer-indicative ex-works base. Landed cost adds freight, insurance, import duty and VAT for your country — your quote itemizes all of it, no surprises at customs."],
      ["Can universities order via purchase order?", "Yes. We work through a registered entity and are used to institutional procurement — POs, vendor registration forms, and multi-signature approval timelines are fine."],
      ["M2 or Ironvale D1?", "M2 for general research, education and content on a tighter budget. D1 if your work is competitive locomotion or you want the more developer-focused stack. Not sure — say so on the form and we'll advise."],
    ],
    meta: {
      title: "Halcyon M2 — Price & Specs | Buy in Europe & Middle East | Humanoid Hub",
      description: "Halcyon M2 humanoid robot: from $12,000, 1.38 m, 24 DOF, Jetson Orin. Buy the M2 in Europe, the Middle East or Africa — formal quote within one business day.",
      ldDescription: "Mid-size humanoid robot, 1.38 m, 24 degrees of freedom, dual Intel N97 + NVIDIA Jetson Orin compute.",
    },
  },
  {
    slug: "vantage-rx2",
    name: "Vantage RX2",
    maker: "Vantage Dynamics",
    kicker: "Vantage Dynamics — multi-modal biped platform",
    cls: "Multi-modal biped platform",
    chips: ["Locomotion R&D", "All-terrain", "Research"],
    badges: ["CE docs verified", "Standard & EDU editions"],
    proof: "Three locomotion modes on one chassis",
    rating: null,
    reviewCount: null,
    image: null,
    gallery: [],
    price: "from $21,600",
    priceNum: "21600",
    priceNote:
      "Manufacturer-indicative, ex-works; Standard and EDU editions. Formal quote reflects edition, freight and duties.",
    lede: "Not a humanoid — a legged locomotion laboratory. The RX2 is a multi-modal biped whose interchangeable configurations let one machine cover point-foot, sole-foot and wheeled research. If your work is locomotion itself, this is designed to be the most versatile all-terrain platform in its price band.",
    useCases: [
      ["Locomotion R&D", "One platform for multiple leg paradigms — swap modes instead of buying three robots."],
      ["Control & RL courses", "An EDU edition exists precisely for teaching labs and coursework."],
      ["Field robotics", "All-terrain capability for inspection and rough-ground research studies."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Edition advice: Standard vs EDU",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Class", "Multi-modal biped research platform"],
      ["Locomotion", "Interchangeable modes — point-foot, sole-foot, wheeled"],
      ["Terrain", "All-terrain, general-purpose bipedal mobility"],
      ["Extensibility", "Open development platform for hardware & software research"],
      ["Editions", "Standard and EDU"],
      ["Indicative price", "from $21,600 ex-works"],
    ],
    diagram: { kind: "biped", dim: "biped platform" },
    faq: [
      ["How do I buy the Vantage RX2 in Europe?", "Request a quote here. We confirm edition availability and lead time with Vantage Dynamics, check documentation for your destination, and return a formal quote — typically in one business day."],
      ["Standard or EDU edition?", "EDU targets teaching labs and coursework; Standard targets research groups extending the platform. Tell us what you're doing on the form and we'll recommend one — the wrong edition is an expensive mistake we exist to prevent."],
      ["Why a biped platform instead of a full humanoid?", "If your research question is locomotion, balance or terrain, arms are cost you don't need. The RX2 puts the budget into legs and modularity. If you need manipulation or human form, look at the M2 or F3 instead."],
      ["Does it really replace three robots?", "For leg-paradigm research, that's the design intent: point-foot, sole-foot and wheeled configurations on one chassis, swapped in your lab rather than procured separately."],
    ],
    meta: {
      title: "Vantage RX2 — Price & Specs | Multi-Modal Biped in Europe | Humanoid Hub",
      description: "Vantage Dynamics RX2 multi-modal biped: from $21,600, three interchangeable locomotion modes, all-terrain research platform. Buy the RX2 in Europe or the Middle East.",
      ldDescription: "Multi-modal biped research platform with interchangeable locomotion modes. All-terrain general-purpose bipedal platform for robotics research.",
    },
  },
  {
    slug: "ironvale-d1",
    name: "Ironvale D1",
    maker: "Ironvale Robotics",
    kicker: "Ironvale Robotics — developer humanoid",
    cls: "Developer humanoid · 23 DOF",
    chips: ["Research", "Competition"],
    badges: ["CE docs verified", "ROS2 · open API"],
    proof: "Built for competitive locomotion research",
    rating: null,
    reviewCount: null,
    image: null,
    gallery: [],
    price: "from $22,000",
    priceNum: "22000",
    priceNote:
      "Manufacturer-indicative, ex-works; current-year configurations from $29,800. Formal quote reflects configuration, freight and duties.",
    lede: "The platform designed for one audience — developers. Complete API, ROS2 compatibility, simulation tooling, and 200 TOPS of Jetson AGX Orin compute, on a frame that walks, runs at up to 18 km/h, and takes a fall without drama.",
    useCases: [
      ["Research teams", "Locomotion and RL research on hardware built for real-world testing."],
      ["Competition squads", "A serious contender for humanoid locomotion and robotics competitions."],
      ["Developer labs", "A serious SDK, sim stack and API — not a demo unit with a locked firmware."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Configuration advice before you commit",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Height / weight", "1.18 m / 30 kg"],
      ["Degrees of freedom", "23"],
      ["Speed", "up to 18 km/h"],
      ["Battery", "~2 h runtime"],
      ["Compute", "NVIDIA Jetson AGX Orin, up to 200 TOPS"],
      ["Software", "Complete API, ROS2 compatibility, simulation & AI tooling"],
      ["Indicative price", "from $22,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 86, torso: [122, 116, 56, 76], dim: "1.18 m", dimTop: 64 },
    faq: [
      ["How do I buy the Ironvale D1 in Europe?", "Request a quote here. We confirm the current configuration matrix and lead time with Ironvale, verify EU compliance documentation, and return a formal itemized quote — typically within one business day."],
      ["Why do I see different D1 prices online?", "Configurations change between model years; current-year configurations list from $29,800 while earlier bases were around $22,000. Your quote states exactly what's in the box for the price — that's the point of getting one."],
      ["Is the D1 good beyond robotics competitions?", "Yes — the competition-oriented design is really a proof of robustness. The ROS2 stack and open API make it a general locomotion and RL research platform; competitions are just where it's built to be stress-tested."],
      ["D1 or Halcyon F3?", "Different classes: D1 is a 1.18 m developer workhorse; F3 is a full-size research humanoid at over twice the price. If you need human scale, F3. For algorithms, competition and most lab work, D1."],
    ],
    meta: {
      title: "Ironvale D1 — Price & Specs | Developer Humanoid in Europe | Humanoid Hub",
      description: "Ironvale D1 developer humanoid: from $22,000, 23 DOF, Jetson AGX Orin (200 TOPS), ROS2. Buy the D1 in Europe or the Middle East.",
      ldDescription: "Developer-focused humanoid robot. 1.18 m, 23 DOF, NVIDIA Jetson AGX Orin, ROS2 stack.",
    },
  },
  {
    slug: "halcyon-f3",
    name: "Halcyon F3",
    maker: "Halcyon Robotics",
    kicker: "Halcyon Robotics — full-size humanoid",
    cls: "Full-size humanoid · 32 DOF",
    chips: ["Advanced R&D", "Industry pilots", "Research"],
    badges: ["CE docs verified", "Full-size flagship"],
    proof: "Most human-like gait in its class",
    rating: null,
    reviewCount: null,
    image: null,
    gallery: [],
    price: "from $54,000",
    priceNum: "54000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "Halcyon's full-size platform, designed for the most human-like walk in its class. A bio-inspired neural-network gait, 32 degrees of freedom, and full 3D perception — at roughly a third of the price of Western full-size humanoids. This is the serious-lab option.",
    useCases: [
      ["Advanced R&D", "Whole-body control, manipulation and embodied-AI research on a full-size frame."],
      ["Industry pilots", "Human-scale testbeds for inspection, logistics and manufacturing studies."],
      ["Flagship exhibits", "A full-size humanoid that walks convincingly is a different league of exhibit."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "EU deliveries: CE documentation verified first",
      "Institutional procurement supported",
    ],
    specs: [
      ["Class", "Full-size humanoid"],
      ["Degrees of freedom", "32"],
      ["Gait", "Bio-inspired neural-network gait — human-like walking, running, squatting"],
      ["Structure", "Aerospace-grade aluminum frame"],
      ["Perception", "360° LiDAR + Intel RealSense depth cameras, 3D obstacle avoidance"],
      ["Intended use", "Research, industrial automation, human-robot interaction"],
      ["Indicative price", "from $54,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 42, torso: [118, 72, 64, 104], dim: "full-size class", dimTop: 22 },
    faq: [
      ["How do I buy the Halcyon F3 in Europe or the Gulf?", "Request a quote here. We confirm build slots and configuration directly with Halcyon, check the compliance documentation for your destination, and return a formal, itemized quote — typically in one business day."],
      ["How does the F3 compare on price to Western full-size humanoids?", "Full-size platforms from US and European makers typically start well above $150,000 when they're purchasable at all. The F3's indicative base is $54,000 — the gap is the reason Chinese platforms dominate research procurement right now."],
      ["What about support and spare parts in Europe?", "Ask us on the form — support terms and spares availability depend on configuration and are itemized in your quote before you commit to anything."],
      ["Is the F3 overkill for our lab?", "If your work doesn't need a full-size frame, the M2 at $12,000 covers most research and education workloads. We'll tell you honestly which one fits — a right-sized first order is how we keep customers."],
    ],
    meta: {
      title: "Halcyon F3 — Price & Specs | Full-Size Humanoid in Europe | Humanoid Hub",
      description: "Halcyon F3 full-size humanoid: from $54,000, 32 DOF, neural-network gait, 360° LiDAR. Buy the F3 in Europe or the Middle East — formal quote in one business day.",
      ldDescription: "Full-size humanoid robot with 32 degrees of freedom, bio-inspired neural-network gait, 360° LiDAR and depth-camera perception.",
    },
  },
];

export const getRobot = (slug) => ROBOTS.find((r) => r.slug === slug);
