export const ROBOTS = [
  {
    slug: "booster-k1",
    name: "Booster K1",
    maker: "Booster Robotics",
    kicker: "Booster Robotics — compact humanoid",
    cls: "Compact humanoid · 22 DOF",
    chips: ["Education", "Competition"],
    badges: ["CE docs verified", "Multi-unit pricing"],
    proof: "Built for RoboCup and classroom fleets",
    rating: null,
    reviewCount: null,
    image: "/robots/booster-k1.webp",
    gallery: ["/robots/booster-k1.webp"],
    price: "from $5,000",
    priceNum: "5000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "The lowest-cost real humanoid we represent — and the easiest first “yes” for a department budget. Force-controlled joints, a full sensor suite, and the same developer DNA as Booster's RoboCup-winning T1, in a compact ~20 kg frame a classroom can handle safely.",
    useCases: [
      ["Education", "Teaching platforms for robotics, control and AI courses — priced so a program can buy several."],
      ["Competition", "Built with RoboCup and university competitions squarely in mind."],
      ["Entry research", "HRI and locomotion work before committing to a full-size platform."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Multi-unit education pricing available on request",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Class", "Compact humanoid, ~20 kg"],
      ["Degrees of freedom", "22, force-controlled joints"],
      ["Motion", "Human-like walking and gestures"],
      ["Perception", "3D depth camera, 9-axis IMU, microphone array, touch sensors"],
      ["Intended use", "Education, research, competition"],
      ["Indicative price", "from $5,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 118, torso: [124, 150, 52, 64], dim: "compact class", dimTop: 96 },
    faq: [
      ["Is $5,000 really the price of a humanoid robot?", "As the indicative ex-works base for the K1, yes — it's the entry point of the current Chinese humanoid wave. Landed cost in the EU adds freight, duty and VAT; your quote itemizes the real delivered number for your country."],
      ["Can a school or university buy several for a course?", "That's the K1's natural habitat. Tell us the quantity on the quote form — multi-unit education pricing is one of the first things we negotiate with the factory."],
      ["K1 or PM01 for a first robot?", "K1 if budget rules or you're equipping a class. PM01 if you want a bigger frame and more onboard compute for research-grade AI workloads. Both are safe first orders."],
      ["How long does delivery to Europe take?", "It depends on factory stock and freight mode — air versus sea is the big fork. Your quote states the current lead time before you commit."],
    ],
    meta: {
      title: "Booster K1 — Price & Specs | Humanoid Robot for Education | Humanoid Hub",
      description: "Booster K1 compact humanoid: from $5,000, 22 DOF, depth camera, built for education and RoboCup. Buy the K1 in Europe or the Middle East — quote in one business day.",
      ldDescription: "Compact humanoid robot for education, research and competition. 22 degrees of freedom, force-controlled joints, 3D depth camera.",
    },
  },
  {
    slug: "engineai-pm01",
    name: "EngineAI PM01",
    maker: "EngineAI Robotics",
    kicker: "EngineAI Robotics — mid-size humanoid",
    cls: "Mid-size humanoid · 24 DOF",
    chips: ["Research", "Content", "Education"],
    badges: ["CE docs verified", "Hub first pick"],
    proof: "First humanoid to land a front flip",
    rating: null,
    reviewCount: null,
    image: "/robots/engineai-pm01.png",
    gallery: ["/robots/engineai-pm01.png"],
    price: "from $12,000",
    priceNum: "12000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "The robot that made humanoids affordable. 1.38 m, 24 degrees of freedom, a 320° rotating waist, and enough onboard compute to run real AI workloads — at a price a single research grant covers. The PM01 is the platform we recommend first to most labs and education programs in EMEA.",
    useCases: [
      ["Research labs", "Locomotion, HRI and embodied-AI work on a budget that leaves room for a second unit."],
      ["Education", "Engineering and robotics programs that need hardware students can actually touch."],
      ["Content & events", "The PM01's dynamics (yes, the front-flip) draw crowds at expos and on camera."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "EU deliveries: CE documentation verified first",
      "University procurement paperwork supported",
    ],
    specs: [
      ["Height", "1.38 m"],
      ["Weight", "40 kg"],
      ["Degrees of freedom", "24 total, incl. 320° waist rotation"],
      ["Compute", "Dual-processor: Intel N97 + NVIDIA Jetson Orin"],
      ["Mobility", "Dynamic walking and high-agility maneuvers (first humanoid to land a front flip)"],
      ["Intended use", "Commercial, research and educational deployment"],
      ["Indicative price", "from $12,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 60, torso: [122, 92, 56, 86], dim: "1.38 m", dimTop: 38 },
    faq: [
      ["How do I buy the EngineAI PM01 in Europe?", "Request a quote through us. We confirm current configuration and lead time with the manufacturer, verify the CE documentation needed for your EU destination, and return a formal quote — typically within one business day."],
      ["What does the PM01 really cost delivered?", "The $12,000 figure is the manufacturer-indicative ex-works base. Landed cost adds freight, insurance, import duty and VAT for your country — your quote itemizes all of it, no surprises at customs."],
      ["Can universities order via purchase order?", "Yes. We work through a registered entity and are used to institutional procurement — POs, vendor registration forms, and multi-signature approval timelines are fine."],
      ["PM01 or Booster T1?", "PM01 for general research, education and content on a tighter budget. T1 if your work is competitive locomotion or you want the RoboCup-proven developer stack. Not sure — say so on the form and we'll advise."],
    ],
    meta: {
      title: "EngineAI PM01 — Price & Specs | Buy in Europe & Middle East | Humanoid Hub",
      description: "EngineAI PM01 humanoid robot: from $12,000, 1.38 m, 24 DOF, Jetson Orin. Buy the PM01 in Europe, the Middle East or Africa — formal quote within one business day.",
      ldDescription: "Mid-size humanoid robot, 1.38 m, 24 degrees of freedom, dual Intel N97 + NVIDIA Jetson Orin compute.",
    },
  },
  {
    slug: "limx-tron1",
    name: "LimX TRON 1",
    maker: "LimX Dynamics",
    kicker: "LimX Dynamics — multi-modal biped platform",
    cls: "Multi-modal biped platform",
    chips: ["Locomotion R&D", "All-terrain", "Research"],
    badges: ["CE docs verified", "Standard & EDU editions"],
    proof: "Three locomotion modes on one chassis",
    rating: null,
    reviewCount: null,
    image: "/robots/limx-tron1.webp",
    gallery: ["/robots/limx-tron1.webp"],
    price: "from $21,600",
    priceNum: "21600",
    priceNote:
      "Manufacturer-indicative, ex-works; Standard and EDU editions. Formal quote reflects edition, freight and duties.",
    lede: "Not a humanoid — a legged locomotion laboratory. The TRON 1 is a multi-modal biped whose interchangeable configurations let one machine cover point-foot, sole-foot and wheeled research. If your work is locomotion itself, this is the most versatile all-terrain platform in its price band.",
    useCases: [
      ["Locomotion R&D", "One platform for multiple leg paradigms — swap modes instead of buying three robots."],
      ["Control & RL courses", "An EDU edition exists precisely for teaching labs and coursework."],
      ["Field robotics", "All-terrain capability for inspection and rough-ground research studies."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Edition advice: Standard vs EDU",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Class", "Multi-modal biped research platform"],
      ["Locomotion", "Interchangeable modes — point-foot, sole-foot, wheeled"],
      ["Terrain", "All-terrain, general-purpose bipedal mobility"],
      ["Extensibility", "Open development platform for hardware & software research"],
      ["Editions", "Standard and EDU"],
      ["Indicative price", "from $21,600 ex-works"],
    ],
    diagram: { kind: "biped", dim: "biped platform" },
    faq: [
      ["How do I buy the LimX TRON 1 in Europe?", "Request a quote here. We confirm edition availability and lead time with LimX Dynamics, check documentation for your destination, and return a formal quote — typically in one business day."],
      ["Standard or EDU edition?", "EDU targets teaching labs and coursework; Standard targets research groups extending the platform. Tell us what you're doing on the form and we'll recommend one — the wrong edition is an expensive mistake we exist to prevent."],
      ["Why a biped platform instead of a full humanoid?", "If your research question is locomotion, balance or terrain, arms are cost you don't need. The TRON 1 puts the budget into legs and modularity. If you need manipulation or human form, look at the PM01 or SE01 instead."],
      ["Does it really replace three robots?", "For leg-paradigm research, that's the design intent: point-foot, sole-foot and wheeled configurations on one chassis, swapped in your lab rather than procured separately."],
    ],
    meta: {
      title: "LimX TRON 1 — Price & Specs | Multi-Modal Biped in Europe | Humanoid Hub",
      description: "LimX Dynamics TRON 1 multi-modal biped: from $21,600, three interchangeable locomotion modes, all-terrain research platform. Buy the TRON 1 in Europe or the Middle East.",
      ldDescription: "Multi-modal biped research platform with interchangeable locomotion modes. All-terrain general-purpose bipedal platform for robotics research.",
    },
  },
  {
    slug: "booster-t1",
    name: "Booster T1",
    maker: "Booster Robotics",
    kicker: "Booster Robotics — developer humanoid",
    cls: "Developer humanoid · 23 DOF",
    chips: ["Research", "RoboCup", "Competition"],
    badges: ["CE docs verified", "ROS2 · open API"],
    proof: "RoboCup 2025 champion platform",
    rating: null,
    reviewCount: null,
    image: "/robots/booster-t1.webp",
    gallery: ["/robots/booster-t1.webp"],
    price: "from $22,000",
    priceNum: "22000",
    priceNote:
      "Manufacturer-indicative, ex-works; current-year configurations from $29,800. Formal quote reflects configuration, freight and duties.",
    lede: "The platform that won RoboCup 2025. Built by a Tsinghua spinout for one audience — developers. Complete API, ROS2 compatibility, simulation tooling, and 200 TOPS of Jetson AGX Orin compute, on a frame that walks, runs at up to 18 km/h, and takes a fall without drama.",
    useCases: [
      ["Research teams", "Locomotion and RL research on hardware proven in actual competition."],
      ["RoboCup squads", "The reigning champion platform — the reference choice for humanoid soccer."],
      ["Developer labs", "A serious SDK, sim stack and API — not a demo unit with a locked firmware."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "Configuration advice before you commit",
      "EU deliveries: CE documentation verified first",
    ],
    specs: [
      ["Height / weight", "1.18 m / 30 kg"],
      ["Degrees of freedom", "23"],
      ["Speed", "up to 18 km/h"],
      ["Battery", "~2 h runtime"],
      ["Compute", "NVIDIA Jetson AGX Orin, up to 200 TOPS"],
      ["Software", "Complete API, ROS2 compatibility, simulation & AI tooling"],
      ["Track record", "RoboCup 2025 champion platform"],
      ["Indicative price", "from $22,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 86, torso: [122, 116, 56, 76], dim: "1.18 m", dimTop: 64 },
    faq: [
      ["How do I buy the Booster T1 in Europe?", "Request a quote here. We confirm the current configuration matrix and lead time with Booster, verify EU compliance documentation, and return a formal itemized quote — typically within one business day."],
      ["Why do I see different T1 prices online?", "Configurations changed between model years; current-year configurations list from $29,800 while earlier bases were around $22,000. Your quote states exactly what's in the box for the price — that's the point of getting one."],
      ["Is the T1 good beyond robot soccer?", "Yes — the competition pedigree is really a proof of robustness. The ROS2 stack and open API make it a general locomotion and RL research platform; soccer is just where it's been publicly stress-tested."],
      ["T1 or EngineAI SE01?", "Different classes: T1 is a 1.18 m developer workhorse; SE01 is a full-size research humanoid at over twice the price. If you need human scale, SE01. For algorithms, competition and most lab work, T1."],
    ],
    meta: {
      title: "Booster T1 — Price & Specs | RoboCup Champion Humanoid in Europe | Humanoid Hub",
      description: "Booster T1 developer humanoid: from $22,000, 23 DOF, Jetson AGX Orin (200 TOPS), ROS2, RoboCup 2025 champion. Buy the T1 in Europe or the Middle East.",
      ldDescription: "Developer-focused humanoid robot. 1.18 m, 23 DOF, NVIDIA Jetson AGX Orin, ROS2 stack. RoboCup 2025 champion platform.",
    },
  },
  {
    slug: "engineai-se01",
    name: "EngineAI SE01",
    maker: "EngineAI Robotics",
    kicker: "EngineAI Robotics — full-size humanoid",
    cls: "Full-size humanoid · 32 DOF",
    chips: ["Advanced R&D", "Industry pilots", "Research"],
    badges: ["CE docs verified", "Full-size flagship"],
    proof: "Most human-like gait in its class",
    rating: null,
    reviewCount: null,
    image: "/robots/engineai-se01.png",
    gallery: ["/robots/engineai-se01.png"],
    price: "from $54,000",
    priceNum: "54000",
    priceNote:
      "Manufacturer-indicative, ex-works. Formal quote includes configuration, freight and duties to your country.",
    lede: "EngineAI's full-size platform, known for the most human-like walk in its class. A bio-inspired neural-network gait, 32 degrees of freedom, and full 3D perception — at roughly a third of the price of Western full-size humanoids. This is the serious-lab option.",
    useCases: [
      ["Advanced R&D", "Whole-body control, manipulation and embodied-AI research on a full-size frame."],
      ["Industry pilots", "Human-scale testbeds for inspection, logistics and manufacturing studies."],
      ["Flagship exhibits", "A full-size humanoid that walks convincingly is a different league of exhibit."],
    ],
    priceboxBullets: [
      "Quote within one business day",
      "EU deliveries: CE documentation verified first",
      "Institutional procurement supported",
    ],
    specs: [
      ["Class", "Full-size humanoid"],
      ["Degrees of freedom", "32"],
      ["Gait", "Bio-inspired neural-network gait — human-like walking, running, squatting"],
      ["Structure", "Aerospace-grade aluminum frame"],
      ["Perception", "360° LiDAR + Intel RealSense depth cameras, 3D obstacle avoidance"],
      ["Intended use", "Research, industrial automation, human-robot interaction"],
      ["Indicative price", "from $54,000 ex-works"],
    ],
    diagram: { kind: "humanoid", headY: 42, torso: [118, 72, 64, 104], dim: "full-size class", dimTop: 22 },
    faq: [
      ["How do I buy the EngineAI SE01 in Europe or the Gulf?", "Request a quote here. We confirm build slots and configuration directly with EngineAI, check the compliance documentation for your destination, and return a formal, itemized quote — typically in one business day."],
      ["How does the SE01 compare on price to Western full-size humanoids?", "Full-size platforms from US and European makers typically start well above $150,000 when they're purchasable at all. The SE01's indicative base is $54,000 — the gap is the reason Chinese platforms dominate research procurement right now."],
      ["What about support and spare parts in Europe?", "Ask us on the form — support terms and spares availability depend on configuration and are itemized in your quote before you commit to anything."],
      ["Is the SE01 overkill for our lab?", "If your work doesn't need a full-size frame, the PM01 at $12,000 covers most research and education workloads. We'll tell you honestly which one fits — a right-sized first order is how we keep customers."],
    ],
    meta: {
      title: "EngineAI SE01 — Price & Specs | Full-Size Humanoid in Europe | Humanoid Hub",
      description: "EngineAI SE01 full-size humanoid: from $54,000, 32 DOF, neural-network gait, 360° LiDAR. Buy the SE01 in Europe or the Middle East — formal quote in one business day.",
      ldDescription: "Full-size humanoid robot with 32 degrees of freedom, bio-inspired neural-network gait, 360° LiDAR and depth-camera perception.",
    },
  },
];

export const getRobot = (slug) => ROBOTS.find((r) => r.slug === slug);
